title: Fish food
hero_image: images/banner.png
description: Control a fish to eat the food using only your voice
version: 1
listed: false
copyedit: false
last_tested: "2024-06-04"
steps:
  - title: Introduction
  - title: Set up the project
  - title: Background noise
  - title: Record the directions
  - title: Train the model
  - title: Move the fish
  - title: Challenge
  - title: What next?
